class MedicinalData:
    PLANT_USES = {
        "Aloevera": ["Skin healing", "Digestion aid", "Boosts immunity"],
        "Amla": ["Rich in Vitamin C", "Improves immunity", "Hair health"],
        "Amruthaballi": ["Fever relief", "Boosts immunity", "Detoxification"],
        "Arali": ["Anti-inflammatory", "Pain relief"],
        "Ashoka": ["Gynecological disorders", "Hormonal balance"],
        "Astma_weed": ["Asthma relief", "Respiratory health"],
        "Badipala": ["Wound healing", "Anti-inflammatory"],
        "Balloon_Vine": ["Joint pain relief", "Anti-rheumatic"],
        "Bamboo": ["Bone health", "Digestive aid"],
        "Beans": ["Protein source", "Heart health"],
        "Betel": ["Digestive aid", "Antibacterial"],
        "Bhrami": ["Improves memory", "Reduces anxiety"],
        "Bringaraja": ["Hair growth", "Liver health"],
        "Camphor": ["Cold relief", "Pain relief"],
        "Caricature": ["Liver detox", "Anti-inflammatory"],
        "Castor": ["Constipation relief", "Skin care"],
        "Catharanthus": ["Anti-cancer properties", "Diabetes control"],
        "Chakte": ["Digestive health"],
        "Chilly": ["Boosts metabolism", "Pain relief"],
        "Citron lime (herelikai)": ["Digestion", "Vitamin C source"],
        "Coffee": ["Mental alertness", "Antioxidant"],
        "Common rue(naagdalli)": ["Menstrual regulation", "Anti-spasmodic"],
        "Coriender": ["Digestion", "Detoxification"],
        "Curry": ["Controls diabetes", "Hair health"],
        "Doddpathre": ["Cold relief", "Digestive aid"],
        "Drumstick": ["Rich nutrients", "Boosts immunity"],
        "Ekka": ["Wound healing", "Anti-inflammatory"],
        "Eucalyptus": ["Respiratory relief", "Antibacterial"],
        "Ganigale": ["Anti-inflammatory"],
        "Ganike": ["Traditional healing"],
        "Gasagase": ["Improves sleep", "Digestive aid"],
        "Ginger": ["Cold relief", "Digestion"],
        "Globe Amarnath": ["Cooling effect", "Anti-inflammatory"],
        "Guava": ["Improves digestion", "Immunity"],
        "Henna": ["Cooling agent", "Hair conditioning"],
        "Hibiscus": ["Hair growth", "Controls BP"],
        "Honge": ["Skin diseases", "Anti-inflammatory"],
        "Insulin": ["Controls diabetes"],
        "Jackfruit": ["Energy booster", "Digestive health"],
        "Jasmine": ["Stress relief", "Skin care"],
        "Kamakastur": ["Anti-inflammatory"],
        "Kambajala": ["Traditional medicine"],
        "Kasambruga": ["Cold relief"],
        "Kepala": ["Digestive aid"],
        "Kohlrabi": ["Bone health"],
        "Lantana": ["Wound healing"],
        "Lemon": ["Vitamin C", "Detox"],
        "Lemongrass": ["Digestion", "Stress relief"],
        "Malabar_Nut": ["Respiratory health"],
        "Malabar_Spinach": ["Iron rich", "Digestion"],
        "Mango": ["Immunity", "Eye health"],
        "Marigold": ["Skin healing", "Anti-inflammatory"],
        "Mint": ["Digestion", "Cooling"],
        "Neem": ["Antibacterial", "Blood purifier"],
        "Nelavembu": ["Fever control", "Immunity"],
        "Nerale": ["Diabetes control"],
        "Nooni": ["Antioxidant", "Immunity"],
        "Onion": ["Heart health", "Immunity"],
        "Padri": ["Traditional medicine"],
        "Palak(Spinach)": ["Iron rich", "Blood health"],
        "Papaya": ["Digestion", "Immunity"],
        "Parijatha": ["Joint pain relief"],
        "Pea": ["Protein rich"],
        "Pepper": ["Cold relief", "Metabolism"],
        "Pomoegranate": ["Blood health", "Antioxidant"],
        "Pumpkin": ["Eye health"],
        "Raddish": ["Liver detox"],
        "Rose": ["Skin care", "Stress relief"],
        "Sampige": ["Cooling effect"],
        "Sapota": ["Energy booster"],
        "Seethaashoka": ["Gynecological health"],
        "Seethapala": ["Digestive health"],
        "Spinach1": ["Iron rich"],
        "Tamarind": ["Digestion"],
        "Taro": ["Gut health"],
        "Tecoma": ["Anti-inflammatory"],
        "Thumbe": ["Cold relief"],
        "Tomato": ["Antioxidant"],
        "Tulsi": ["Immunity", "Respiratory health"],
        "Turmeric": ["Anti-inflammatory", "Wound healing"]
    }

    @classmethod
    def get_uses(cls, plant_name):
        return cls.PLANT_USES.get(plant_name, [])
